---
#NO_PROXY: "{{ansible_hostname}},localaddress,.localdomain.com,example.com,{{ansible_default_ipv4.address}},{{k8s_pod_cidr}},{{ ansible_default_ipv4.address.split('.')[0:3] | join('.') + '.0/24' }}"
NO_PROXY: "{{ansible_hostname}},localaddress,.localdomain.com,example.com,{{ansible_default_ipv4.address}},{{k8s_pod_cidr}},10.244.0.0/16,192.168.0.0/16"
